narrow down macro check, so latest branch keeps building against ongoing 6.18 point versions
without adjustment, since 6.18.44, causes:

```
drivers/gpu/drm/i915/display/intel_fbdev.c: In function ‘intel_fbdev_driver_fbdev_probe’:
drivers/gpu/drm/i915/display/intel_fbdev.c:330:16: error: implicit declaration of function ‘drm_fb_helper_alloc_info’; did you mean ‘drm_fb_helper_fill_info’? [-Wimplicit-function-declaration]
  330 |         info = drm_fb_helper_alloc_info(helper);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~
      |                drm_fb_helper_fill_info
drivers/gpu/drm/i915/display/intel_fbdev.c:330:14: error: assignment to ‘struct fb_info *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  330 |         info = drm_fb_helper_alloc_info(helper);
      |              ^
  CC [M]  drivers/gpu/drm/i915/display/dvo_sil164.o
```